name: 'Configure llvm-project'
description: >
  This action is meant to be a very thin wrapper around CMake that can be used
  to configure the llvm-project.  It will add the minimal set of CMake options
  necessary to build and test llvm-project.
inputs:
  cmake_args:
    description: 'Arguments to pass to CMake when configuring'
    required: false
  os:
    description: 'Host OS'
    required: false
    default: ${{ runner.os }}
runs:
  using: 'node20'
  main: 'main.js'
