name: 'Get LLVM source'
description: 'Download and unpack LLVM sources'
inputs:
  ref:
    description: 'Git ref of source to fetch.  This can also be a tag.  Defaults to github.sha'
    required: false
    default: ${{ github.sha }}
  repo:
    description: 'The repo to fetch code from. e.g. llvm/llvm-project Defaults to github.repository'
    required: false
    default: ${{ github.repository }}

runs:
  using: 'node20'
  main: 'main.js'
